### ISSUE TITLE
Capital letter allowed in template, but not deployable

### ISSUE THREAD

**Issue by Leviani** [dandinu/azurechatgpt#3]
Hi,

you should either add a ToLower to your Azure Template File for the DB Names, or add a description to the "Name" field to not allow capital letter. Otherwise the Deployment fails with a not really usable error message.
![image](https://github.com/dandinu/azurechatgpt/assets/7995792/a738e4d0-8078-4d88-af73-5687c92b1de5)

**Comment by dandinu** [comment]
Hi Leviani, checking on this now
